### PR TITLE
translate 'no parlo inglese' in German

### PR DESCRIPTION
**Pull request by danrocha**
Contributes to #3 

Added German translation.
Not sure if I should also add the Austrian and Swiss flags?

### CODE REVIEW

**Comment by davcri** [comment]
That's a good question. I would say yes, let's be inclusive :smile: 

Thank you for your contribution! And happy Hacktoberfest :tada:

**Comment by danrocha** [comment]
I went on and added all the flags of all countries with German as their official language (Austria, Germany, Liechtenstein, Belgium, Switzerland, Luxembourg).

But I am not sure about this though. If you follow this pattern and look at Spanish, for example, the list of flags would be pretty long. 

What do you think?

**Comment by davcri** [comment]
@danrocha you are right, some language is adopted by many countries. I think a good approach is:

If the language is spoken in more than 3 countries we put the 3 most common nations as a flag and then we add:

> :es: :argentina: :mexico: (... and all the other countries where people speak Spanish): ... 

Maybe we could also add a text at the beginning of the list saying something like:

> :warning:  NOTE: If you don't see a flag representing your nation, I'm really sorry for this. We decided to put 3 flags at max for each language for practical reasons. Feel free to say your opinion and leave a comment in [this issue](https://github.com/crystal-bit/space-shooter/pull/41),

**Comment by davcri** [comment]
@danrocha I'm gonna accept this PR, we can discuss further if needed! Thanks for your help!

**Comment by danrocha** [comment]
@davcri sorry for the delay in replying, I was out traveling with family!

Another solution would be to replace the country flags with the iso code for the language. 
**de**
**es**
**en** 

what do you think?

**Pull request merged**
